-- 데이터 추적(Pulseboard 흡수) — da-ad-planner Supabase에 추가. 전부 pb_ 프리픽스라 기존 테이블과 충돌 없음.
-- ⚠️ 모든 접근은 서버(service_role)로만 → RLS 켜되 "정책 없음" = 브라우저/익명 완전 차단.
--    (공개 수집 입구를 인스타 토큰 등 민감 데이터와 격리)
-- Supabase SQL Editor 에서 1회 실행하세요. (기존 데이터 영향 없음)

create extension if not exists "pgcrypto";

-- 1) 사이트(추적 대상)
create table if not exists pb_sites (
  id                  text primary key,
  name                text not null,
  url                 text,
  logo_url            text,
  head_code           text,
  tracking_verified   boolean not null default false,
  tracking_checked_at timestamptz,
  last_tested_at      timestamptz,
  trashed_at          timestamptz,
  created_at          timestamptz not null default now()
);

-- 2) 원시 이벤트(시계열) — 트래커가 보낸 page_view/click/scroll/page_leave 등
create table if not exists pb_analytics_events (
  id                 uuid primary key default gen_random_uuid(),
  site_id            text not null references pb_sites(id) on delete cascade,
  session_id         text not null,
  visitor_id         text not null,
  event_type         text not null,
  url                text,
  path               text,
  referrer           text,
  device_type        text,
  page_region        text,
  element_label      text,
  scroll_percent     integer,
  funnel_step        text,
  duration_ms        integer,
  max_scroll_percent integer,
  click_x            double precision,
  click_y            double precision,
  viewport_width     integer,
  viewport_height    integer,
  ip_address         text,
  metadata           jsonb not null default '{}'::jsonb,
  created_at         timestamptz not null default now()
);
create index if not exists pb_events_site_created_idx on pb_analytics_events(site_id, created_at desc);
create index if not exists pb_events_session_idx       on pb_analytics_events(session_id);

-- 3) 관리 페이지
create table if not exists pb_managed_pages (
  id             bigint generated by default as identity primary key,
  site_id        text not null references pb_sites(id) on delete cascade,
  page_name      text not null,
  url            text not null,
  capture_url    text,
  matching_type  text not null default 'Starts Match',
  status         text not null default '진행 중',
  tracking_ready boolean not null default false,
  login_required boolean not null default false,
  mobile_only    boolean not null default false,
  weekly_report  boolean not null default false,
  pv             integer not null default 0,
  start_date     date,
  end_date       date,
  group_name     text,
  note           text,
  created_at     timestamptz not null default now()
);
create index if not exists pb_managed_pages_site_idx on pb_managed_pages(site_id, created_at desc);

-- 4) 비밀 페이지
create table if not exists pb_secret_pages (
  id         uuid primary key default gen_random_uuid(),
  site_id    text not null references pb_sites(id) on delete cascade,
  name       text not null,
  url        text not null,
  page_key   text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists pb_secret_pages_site_idx on pb_secret_pages(site_id, created_at desc);

-- RLS: 켜되 정책 없음 → service_role(서버)만 우회 접근. 브라우저(anon/authenticated) 접근 불가.
alter table pb_sites             enable row level security;
alter table pb_analytics_events  enable row level security;
alter table pb_managed_pages     enable row level security;
alter table pb_secret_pages      enable row level security;
